### ISSUE TITLE
Page for editing existing Skill

### ISSUE THREAD

**Issue by marcusgchan** [MLH-Fellowship/orientation-project-js-23.SUM.B.1#12]
https://github.com/MLH-Fellowship/orientation-project-python-23.SUM.B.1/issues/23

**Comment by DeleMike** [comment]
@marcusgchan , I created a like a mini-doc, if you want to know how the endpoint will behave
Look here: https://github.com/MLH-Fellowship/orientation-project-python-23.SUM.B.1/pull/34#issue-1772197784
